### ISSUE TITLE
Feedback from Peer Review

### ISSUE THREAD

**Issue by phuntsoktseten** [UBC-MDS/Car_Insurance_Analysis#16]
1)Mention what 0 and 1 is in the data set(change to accept car insurance offered or not)
2)Rename the scripts and include the number to state the order of the scripts
3) Instead of using absolute number in our visualization use proportion

**Comment by mchiriboga** [comment]
@phuntsoktseten I submitted a [pull request](https://github.com/UBC-MDS/Car_Insurance_Analysis/pull/18) to address these items, please take a look.

**Comment by phuntsoktseten** [comment]
We addressed the above issues from the peer review.
1) We changed the 0 and 1 in the data set to accept car insurance offered or not accept car insurance offered respectively.
2) We renamed the scripts and included the number in each script to specify the order of scripts so that it is easy to read and understand.
3) We also changed our graph from using absolute values to proportion
