### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Car_Insurance_Analysis#6]
@mchiriboga and @phuntsoktseten , you have chosen an interesting data set and you have a good plan. Here are some improvement points and minor suggestions for your project.

- Keep in mind that your readme is the landing page for someone examining your analysis. Therefore, you can do some additions that would make the readme more informative and intriguing for a visitor. In particular, you can include a brief introduction about the context and your motivation to do such analysis. Then, you can introduce your question and explain the data as you have done already.

- I believe you should also mention your significance level in testing the hypotheses. 

**Minor Suggestions:**

- I would recommend taking "DSCI_522" out of the name of your project. But if you like it this way, no problem.

- Include your Github profile links with your names on the readme.

I hope this feedback is helpful in improving your project. Please let me know if you have any questions. Good luck!

**Comment by phuntsoktseten** [comment]
We also renamed the name of the project and deleted "DSCI_522"

**Comment by phuntsoktseten** [comment]
Yeah, sure, I will look at them and address the first two points. Thanks

**Comment by phuntsoktseten** [comment]
1)We made the Readme more informative by adding a brief introduction about the context and motivation for our analysis. We answered  why we were interested in such an analysis.

2) We also added the significance level(alpha) when we are testing our hypotheses.

**Comment by mchiriboga** [comment]
Addressed on 
https://github.com/UBC-MDS/Car_Insurance_Analysis/pull/17
